# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20160710_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Award_Name', models.CharField(max_length=100)),
            ],
        ),
    ]
