# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20161029_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingevents',
            name='EventImage',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
